export const ErrorCode = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_FIELD_TYPE: 'INVALID_FIELD_TYPE',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  UNIQUE_CONSTRAINT_VIOLATION: 'UNIQUE_CONSTRAINT_VIOLATION',

  // Not found
  NOT_FOUND: 'NOT_FOUND',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  BLUEPRINT_NOT_FOUND: 'BLUEPRINT_NOT_FOUND',

  // Conflict
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  SLUG_TAKEN: 'SLUG_TAKEN',

  // Rate limit
  RATE_LIMITED: 'RATE_LIMITED',

  // Security
  SSRF_BLOCKED: 'SSRF_BLOCKED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
